apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
